### ISSUE TITLE
Pandas/Parsy are not an optional dependency

### ISSUE THREAD

**Issue by gabrielgellner** [bis-med-it/pysdmx#105]
In the `pyproject.toml` pandas is declared a optional dependency, as so does not get installed with a `pip install pysdmx` but in the `model/__init__.py` `SeriesInfo` is imported which has a raw import of import pandas as pd meaning this will error if the user does not have pandas manually installed.

Same for parsy.

**Comment by sosna** [comment]
@gabrielgellner: Thanks for reporting this. It is however a duplicate of #97, so I will close this one.

I am also working on a fix for #97 and a new release candidate will be available soon.

**Comment by sosna** [comment]
Duplicate of #97
