### ISSUE TITLE
Problem with parsing facets in fusion-json

### ISSUE THREAD

**Issue by stratosn** [bis-med-it/pysdmx#109]
Representation facets `minValue` and `maxValue` are modelled as `int` or `float` in the `fusion` messages, as seen below:
https://github.com/bis-med-it/pysdmx/blob/1cafa99cdef22086cbf53487ce4a78b641665d79/src/pysdmx/io/json/fusion/messages/core.py#L38C4-L39C49

But the `fusion-json` message treats them as `string`, see example below:
```json
                    "representation": {
                        "textFormat": {
                            "textType": "Double",
                            "sequence": false,
                            "maxValue": "9999",
                            "minValue": "1"
                        }
                    },
```

**Comment by sosna** [comment]
In SDMX-JSON, the equivalent is:

                            "localRepresentation": {
                                    "format": {
                                        "isSequence": false,
                                        "maxValue": 9999,
                                        "minValue": 1,
                                        "dataType": "Double"
                                    }
                                },
