### ISSUE TITLE
Migrate flake8 and black to ruff library

### ISSUE THREAD

**Issue by javihern98** [bis-med-it/pysdmx#136]
Add the ruff library to the dev packages to improve maintainability and time to deliver, as it greatly reduces the time it takes for linting checks and changes. It also automatically fixes (using the --fix function) the linting errors it may find.

Steps to perform:
- Migrate flake8 file to pyproject.toml
- Adapt the ci.yml to use ruff instead of flake8 (do not add the --fix argument here)

**Comment by gabrielgellner** [comment]
Not sure if you are also looking into moving from poetry to uv :) Once you go ruff you will want to :)

**Comment by javihern98** [comment]
> Not sure if you are also looking into moving from poetry to uv :) Once you go ruff you will want to :)

Still I believe poetry is a nice dependency manager, for sure I will look into it, but for now I prefer to keep poetry. @sosna What do you think of uv?

**Comment by sosna** [comment]
I have been using poetry so far, for all the projects I have been involved with. So I can't say I have any opinion on `uv`, at least not yet 😊.

**Comment by javihern98** [comment]
I will proceed now with this issue, after finishing all functionalities
