### ISSUE TITLE
Add support for retrieving provision agreements

### ISSUE THREAD

**Issue by sosna** [bis-med-it/pysdmx#154]
We now have a use case where we need to be able to retrieve provision agreements

**Comment by javihern98** [comment]
@sosna Do we need to add as well the SDMX-ML 2.1 parsers and writers for them?

**Comment by sosna** [comment]
Thanks, @javihern98. I don't think so or, at least, there is no urgency. The reason is that we need this in the `pysdmx.api.fmr` clients, and these clients rely on JSON messages.
