### ISSUE TITLE
XML parsers for data reading

### ISSUE THREAD

**Issue by javihern98** [bis-med-it/pysdmx#50]
- Add XML parsers for data reading on SDMX-ML 2.1 Generic and Structure Specific
- Add Pandas optional dependency

Depends on #46

**Comment by stratosn** [comment]
@javihern98 the invitation to @albertohernandez1995 was sent last Monday, but it is still pending.
@albertohernandez1995 can you check, please?

**Comment by albertohernandez1995** [comment]
Hi @stratosn. I checked it and I have not recieved any invitation. Could
you send it again, please? Thank you.

**Comment by stratosn** [comment]
Hi @albertohernandez1995 cab you check here: https://github.com/settings/organizations
The invitation should be there.
If not, we can send a new one.

**Comment by javihern98** [comment]
Hi @stratosn all good now, thanks!

**Comment by javihern98** [comment]
@sosna @stratosn Would you have somewhere a data file that references a Provision Agreement for testing?

```xml
<message:Structure structureID="AAA"
                   namespace="urn:dummy"
                   dimensionAtObservation="AllDimensions">
    <common:ProvisionAgrement>
        ....................................
    </common:ProvisionAgrement>
</message:Structure>
```

**Comment by stratosn** [comment]
Hi @javihern98, do you need an example on how to reference a Provision Agreement or the actual data file with the related Structures?

**Comment by javihern98** [comment]
Probably the actual file with the related structures, to implement it properly
________________________________

**Comment by stratosn** [comment]
Ok, then we need to prepare something from scratch, but if you already have a dataset that references a Dataflow, then the changes should not be a lot.

**Comment by javihern98** [comment]
Yes, please use this file. This references a dataflow from a dataset


________________________________

**Comment by stratosn** [comment]
Sorry cannot see the file on GH. Maybe you could upload using the UI, or simply send it to me by email.

**Comment by stratosn** [comment]
Thanks, @javihern98 
This file can easily refer to the Provision Agreement, only by changing the header `<message:Structure>` content, ie:
```xml
        <message:Structure structureID="BIS_WEBSTATS_DER_DATAFLOW_1_0"
                           namespace="urn:sdmx:org.sdmx.infomodel.datastructure.Dataflow=BIS:WEBSTATS_DER_DATAFLOW(1.0):ObsLevelDim:TIME_PERIOD"
                           dimensionAtObservation="AllDimensions">
            <common:ProvisionAgrement>
                <Ref agencyID="BIS" id="WEBSTATS_DER_DATAFLOW_PRA" version="1.0"/>
            </common:ProvisionAgrement>
        </message:Structure>
```
Note that the 2.1 schemas include a typo (`ProvisionAgrement` instead of `ProvisionAgreement`)

Of course, this is the only change directly impacted by the referencing, but if you wanted to make it more meaningful, it might be useful to consider further Constraints.
If you need something more on that, please let me know.
