### ISSUE TITLE
Parsing fails when series has no observations in sdmxml format

### ISSUE THREAD

**Issue by flori-ko** [bis-med-it/pysdmx#80]
Parsing the response from an API currently fails if a series has no observations (for example because the start date lies outside the observation range of the series).
The series inside the response could look for example like this:

```
<Series FREQ="M", AREA="US", COLLECTION = "A"/>
<Series FREQ="Q", AREA="US", COLLECTION = "A"/>
```

The parser should ideally ignore the series.
Thank you

**Comment by sosna** [comment]
There is also a valid use case to return series without observations, as a response to an SDMX-REST data query where the `measures` query parameter is set to `none`.

**Comment by javihern98** [comment]
Hi @flori-ko , we will check here only if the parser is able to parse a file like this. The expected output will be a Dataset with no records.

@sosna @stratosn Please check internally with @flori-ko if any other changes are needed

**Comment by flori-ko** [comment]
Hi @javihern98 thank you for following up. I just have two remarks regarding your respone:
1. I don't want to parse a file, but instead a string I've recieved from the api. Is this also possible?
2. Regarding the "the expected output will be a dataset with not records" parts, there can be a lot of series with observations in the response and just a couple (or just one) without. All series with observations should naturally appear in the output.

**Comment by javihern98** [comment]
> Hi @javihern98 thank you for following up. I just have two remarks regarding your respone:
> 
>     1. I don't want to parse a file, but instead a string I've recieved from the api. Is this also possible?
> 
>     2. Regarding the "the expected output will be a dataset with not records" parts, there can be a lot of series with observations in the response and just a couple (or just one) without. All series with observations should naturally appear in the output.

1. Yes, it is currently possible.
2. We will check also this use case, to ensure we are ignoring those records.

**Comment by stratosn** [comment]
As regards the 2nd bullet, according to SDMX, such Series (without Obs) are valid and should be there in an SDMX dataset.
Ignoring them in the parser is not an option, as it means loss of information, eg when they represent a delete message, or an update of Series level Attributes.
Any such filtering should be left outside `pysdmx` and be performed by client systems.

**Comment by javihern98** [comment]
Seems there is in fact an error inside the SDMX-ML parsers when no Observations are found inside a Series. We will check all use cases using the SDMX Schemas and provide new tests.
