### ISSUE TITLE
Implement the VTL artefacts parsers

### ISSUE THREAD

**Issue by javihern98** [bis-med-it/pysdmx#91]
Implement the VTL Artefacts based on SDMX 3.0. Implement XML parsers based on SDMX 2.1 and make a mapping to the new model class.

![image](https://github.com/user-attachments/assets/bcf9310a-a9df-439b-9e7e-604b89cdc1e1)

@sosna Shall we use the [vtlengine](https://github.com/Meaningful-Data/vtlengine) to perform syntax/semantic validations?

**Comment by javihern98** [comment]
@sosna @stratosn  Checking latest version of fmr I see that the SDMX 2.1 file and SDMX 3.0 file of a Transformation Cheme is the same. XML Schemas seem to be the same as well for both 2.1 and 3.0, so I will implement the parsers as seen in the XSD Schemas.

**Comment by sosna** [comment]
@javihern98, just to be sure we don't do double work, in my branch to solve #92:

- I have implemented all the model classes (as per the UML diagram above);
- I am adding deserializers for SDMX-JSON and Fusion-JSON for VTL Structure Messages;
- Last, I will add a method to `pysdmx.api.fmr` to fetch transformation schemes (and their children) from the FMR;

This is as you expected, isn't it?

Once this is done (next week, hopefully), then the idea would be to leverage this but linking it with your open-source VTL engine 😊.

In case the above is not as expected, happy to discuss!

**Comment by javihern98** [comment]
Yes, this is as expected. I also implemented some of the classes but happy to await for your PR to connect the parsers.

We will only develop the parsers for TransformationScheme and Transformation as we have serious concerns about the usefulness of the other objects and their usability by the final user.
